# -*- coding: utf-8 -*-
import sys
import time

def dp(s,t=0.05):
    for c in s:
        sys.stdout.write( '%s' % c )
        sys.stdout.flush()
        time.sleep(t)

dp("\n\nHi there. <-- our he-heroine\n\n")
time.sleep(0.8)
dp("Hi back. <-- our anti-hero\n\n")
time.sleep(0.8)
dp("Where are you headed? <-- he-heroine\n\n")
time.sleep(0.8)
dp("Why would you ask that? <-- anti-hero\n\n")
time.sleep(0.8)
dp("Are you going home? <-- he-heroine. Get the gist?\n\n")
time.sleep(0.8)
dp("Why do you want to know?\n\n")
time.sleep(0.8)
dp("I'm wondering if I might come with you.\n\n")
time.sleep(0.8)
dp("Excuse me?\n\n")
time.sleep(0.8)
dp("I'd like to know where you're going.\n")
dp("If you're going home, I'd like to go with you.\n\n")
time.sleep(0.8)
dp("I heard you the first time.\n")
dp("I meant, why would you ask me that?\n\n")
time.sleep(0.8)
dp("What do you mean?\n\n")
time.sleep(0.8)
dp("I mean, why would you ask me if I'm going home\n")
dp("and why would you ask if you can come with me?\n\n")
time.sleep(0.8)
dp("Because I don't want to lose you.\n\n")
time.sleep(0.8)
dp("Lose me?!\n\n")
time.sleep(0.8)
dp("I can recognize you.")
time.sleep(0.8)
dp(" At least, I think I can.\n\n")
time.sleep(0.8)
dp("What?\n\n")
time.sleep(0.8)
dp("For the last two days, I've been able to pick you out of a crowd,")
dp("\nout of a class, wherever.\n\n")
time.sleep(0.8)
dp("You've been following me?")
time.sleep(0.8)
dp(" How?\n\n")
time.sleep(0.8)
dp("Yesterday, I was at the school courtyard,\nand I realized that I")
dp(" kept picking out the same man.\nI passed you on a bench while you were")
dp(" eating.\nI had to look back because I felt like...\nlike I had seen you before.\n\n")
time.sleep(0.8)
dp("That's impossible!\n\n")
time.sleep(0.8)
dp("That's what I thought.\nBut then, I kept picking you out.\n")
dp("I couldn't control it.\nI would look and just know that I had seen you before.\n\n")
time.sleep(0.8)
dp("What is this, a joke?\n\n")
time.sleep(0.8)
dp("No, I swear.\nAnd now that I can recognize you,\nand now that we've met,\n")
time.sleep(0.8)
dp("I can't go losing you.\n\n")
time.sleep(0.8)
dp("Look lady. You are seriously confused.\n")
dp("How long have you been out?\n\n")
time.sleep(0.8)
dp("Out?\n\n")
time.sleep(0.8)
dp("How long since you emerged?\n\n")
time.sleep(0.8)
dp("Oh. Three days, maybe.\n\n")
time.sleep(0.8)
dp("That explains it.\nLook, nobody can recognize anybody.\n")
dp("Whatever you think is going on,")
time.sleep(0.8)
dp(" it's not.\n\n")
time.sleep(0.8)
dp("I am telling you that I can recognize you.\n")
dp("You look the same as every other man,\n")
dp("but somehow,")
time.sleep(0.8)
dp(" somehow, I know who you are.\n\n")
time.sleep(0.8)
dp("This has to be some sort of recent emergence attachment issue.\n")
dp("You've only been out three days.\n")
dp("It makes perfect sense. You'll get used to it.\n")
time.sleep(0.8)
dp("Now, I really wish I could help you...\n\n")
time.sleep(0.8)
dp("Wait! Don't go. Stop! Just check your pocket.\n\n")
time.sleep(0.8)
dp("I'm sorry?\n\n")
time.sleep(0.8)
dp("Check the left coat pocket.\n\n")
dp("Okay.")
time.sleep(0.8)
dp(" I've had enough.\n")
dp("You're delirious. And, if you don't stop, I will shout Lunatic.\n\n")
dp("Please. Just check it!\n\n")
dp("I can't believe I'm doing this. But, if it'll please you I'll...")
time.sleep(0.9)
dp(" What the?\n\n")
time.sleep(0.8)
dp("See?\n\n")
time.sleep(0.8)
dp("Yes, I see there is a piece of paper in my pocket.\n")
dp("You're some kind of psychic,")
time.sleep(0.6)
dp(" guessing there might be a piece of paper in my pocket.\n")
dp("What next?\n")
time.sleep(0.8)
dp("Are you going to guess that my shoes are tied?\n\n")
dp("Please read it.\n\n")
dp("No.")
time.sleep(0.8)
dp(" Whatever it is that you're up to\n")
time.sleep(0.8)
dp("you'll just have to play crazy without me.\n\n")
time.sleep(0.8)
dp("Please. Just read it.\n\n")
time.sleep(0.8)
dp("Why? Why should I entertain this?\n")
dp("You don't think I know that you slipped a note into my pocket back\n")
dp("there on the sidewalk?\n\n")
time.sleep(0.8)
dp("Just read it and you'll that it won't matter when I slipped it")
dp(" into your pocket.\n\n")
time.sleep(0.8)
dp("No. I've had enough of this.\n\n")
time.sleep(0.8)
dp("It says that I saw you eating breakfast in the courtyard,\n")
dp("that I sat next to you in psychology class this morning,\n")
dp("and we shared a bench in the cafe.\n")
time.sleep(0.8)
dp("You were writing in a notebook.\n\n")
time.sleep(0.8)
dp("How dare you! How dare you stalk me! That's it!\n\n")
dp("No, no. Please don't.\n\n")
time.sleep(0.8)
dp("Lunatic! ")
time.sleep(0.8)
dp("Lunatic! ")
time.sleep(0.8)
dp("Lunatic!\n\n")
dp("Why did you do that?\n\n")
dp("Because you've lost it!\n\n")
dp("No, I haven't!\n")
time.sleep(0.8)
dp("I can recognize you. ")
time.sleep(0.8)
dp("I just proved it.\n\n")
time.sleep(0.8)
dp("No. You proved you're a Lunatic and that you've been stalking me!\n\n")
time.sleep(0.8)
dp("No. You don't understand!\n\n")
time.sleep(0.8)
dp("You'd better run. You've got maybe a minute.\n\n")
dp("Well, just don't stand there. ")
time.sleep(1.0)
dp("Go!\n\n")
time.sleep(1.0)

dp("Okay, so things are starting out rough for our he-heroine and anti-hero.\n")
time.sleep(0.8)
dp("And within this Neutral society, there is now one person who can be")
dp(" recognized\nand one person who can recognize someone else.\n\n")
time.sleep(0.8)
dp("And, if this isn't enough to start mixing things up,")
time.sleep(0.8)