import sys
import time

def dp(s,t=0.05):
    for c in s:
        sys.stdout.write( '%s' % c )
        sys.stdout.flush()
        time.sleep(t)


t1 = 0.5
dp("\nHi there. <-- our he-heroine\n\n")
time.sleep(0.8)
dp("Hi back. <-- our anti-hero\n\n")
time.sleep(0.8)
dp("Where are you going? <-- he-heroine\n\n")
time.sleep(0.8)
dp("Why would you ask that? <-- anti-hero\n\n")
time.sleep(0.8)
dp("Are you going home? <-- Get the gist?\n\n")
time.sleep(0.8)
dp("Why do you want to know?\n\n")
time.sleep(0.8)
dp("I'm wondering if I might come with you.\n\n")
time.sleep(0.8)
dp("Excuse me?\n\n")
time.sleep(0.8)
dp("I'd like to know where you're going.\n")
dp("If you're going home, I'd like to go with you.\n\n")
time.sleep(0.8)
dp("I heard you the first time.\nI meant, why would you ask me that?\n\n")
time.sleep(0.8)
dp("What do you mean?\n\n")
time.sleep(0.8)
dp("I mean, why would you ask me if I'm going home\nand why would you ")
dp("ask if you can come with me?\n\n")
time.sleep(0.8)
dp("Because I don't want to lose you.\n\n")
time.sleep(0.8)
dp("Lose me?\n\n")
time.sleep(0.8)
dp("I can recognize you, at least, I think I can.\nI'm pretty sure of it.\n\n")
time.sleep(0.8)
dp("What?\n\n")
time.sleep(0.8)
dp("For the last two days, I've been able to pick you out of a crowd,\nout of class, wherever.\n\n")
time.sleep(0.8)
dp("You've been following me? How?\n\n")
time.sleep(0.8)
dp("Yesterday, I was at the school courtyard,\nand I realized that I")
dp(" kept picking out the same man.\nI passed you on a bench while you were")
dp(" eating.\nI had to look back because I felt like...\nlike I had seen you before.\n\n")
time.sleep(0.8)
dp("That's impossible!\n\n")
time.sleep(0.8)
dp("That's what I thought.\nBut then, I kept picking you out.\n")
dp("I couldn't control it.\nI would look and just know that I had seen you before.\n\n")
time.sleep(0.8)
dp("What is this, a joke?\n\n")
time.sleep(0.8)
dp("No, I swear.\nAnd now that I can recognize you,\nand now that we've met,\n")
dp("I can't go losing you.\n\n")
time.sleep(0.8)
dp("Look lady. You are really confused.\n")
dp("How long have you been out?\n\n")
time.sleep(0.8)
dp("Out?\n\n")